// GENERATED by scripts/build-spell-packs.ts — do not edit.
import type { DataPack } from "../../lexicon/pack-schema";
import p_abbreviations from "./abbreviations.json";
import p_derived_deverbal from "./derived-deverbal.json";
import p_general_core from "./general-core.json";
import p_general_corpus from "./general-corpus.json";
import p_general from "./general.json";
import p_legal from "./legal.json";
import p_proper_nouns from "./proper-nouns.json";
import p_vocab_abbr from "./vocab-abbr.json";
import p_vocab_academic from "./vocab-academic.json";
import p_vocab_business from "./vocab-business.json";
import p_vocab_general from "./vocab-general.json";
import p_vocab_government from "./vocab-government.json";
import p_vocab_legal from "./vocab-legal.json";
import p_vocab_medical from "./vocab-medical.json";
import p_vocab_names from "./vocab-names.json";
import p_vocab_tech from "./vocab-tech.json";

export const ALL_PACKS: readonly DataPack[] = [p_abbreviations, p_derived_deverbal, p_general_core, p_general_corpus, p_general, p_legal, p_proper_nouns, p_vocab_abbr, p_vocab_academic, p_vocab_business, p_vocab_general, p_vocab_government, p_vocab_legal, p_vocab_medical, p_vocab_names, p_vocab_tech] as unknown as DataPack[];
