import { createHash, createPublicKey, verify } from "node:crypto";

/**
 * Device identity = an Ed25519 key pair generated by the desktop app at
 * install time (private key in OS secure storage). Identity is the key, not
 * hardware: OS reinstall yields a new identity (handled as a device change),
 * and replacing a disk/RAM/NIC does not. See docs/spell/adr-007.
 *
 * Wire formats: base64url, no padding.
 */

export const SPELL_REQUEST_SIGNATURE_VERSION = "TORE-SPELL-V1";
const ED25519_RAW_PUBLIC_KEY_LENGTH = 32;
const ED25519_SIGNATURE_LENGTH = 64;
const BASE64URL = /^[A-Za-z0-9_-]+$/;

export function isBase64Url(value: unknown, maxLength = 512): value is string {
  return (
    typeof value === "string" &&
    value.length > 0 &&
    value.length <= maxLength &&
    BASE64URL.test(value)
  );
}

export function decodeBase64Url(value: string): Buffer {
  return Buffer.from(value, "base64url");
}

export function encodeBase64Url(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64url");
}

/** Parse a raw Ed25519 public key; returns null for anything malformed. */
export function parseRawEd25519PublicKey(publicKey: unknown): Buffer | null {
  if (!isBase64Url(publicKey, 64)) return null;
  const raw = decodeBase64Url(publicKey);
  if (raw.length !== ED25519_RAW_PUBLIC_KEY_LENGTH) return null;
  // Re-encoding must round-trip, rejecting non-canonical encodings.
  if (encodeBase64Url(raw) !== publicKey) return null;
  return raw;
}

export function computeKeyThumbprint(rawPublicKey: Uint8Array): string {
  return createHash("sha256").update(rawPublicKey).digest("base64url");
}

/**
 * Canonical string the client signs. Binds method, path, time, nonce and the
 * exact body, so a captured request cannot be replayed on another endpoint,
 * with another body, or later.
 */
export function buildCanonicalRequest(input: {
  method: string;
  path: string;
  timestamp: string;
  nonce: string;
  rawBody: string;
}): string {
  const bodyHash = createHash("sha256").update(input.rawBody, "utf8").digest("hex");
  return [
    SPELL_REQUEST_SIGNATURE_VERSION,
    input.method.toUpperCase(),
    input.path,
    input.timestamp,
    input.nonce,
    bodyHash,
  ].join("\n");
}

export function verifyEd25519Signature(input: {
  publicKey: string;
  message: string;
  signature: string;
}): boolean {
  const raw = parseRawEd25519PublicKey(input.publicKey);
  if (!raw || !isBase64Url(input.signature, 128)) return false;
  const signature = decodeBase64Url(input.signature);
  if (signature.length !== ED25519_SIGNATURE_LENGTH) return false;
  try {
    const key = createPublicKey({
      key: { kty: "OKP", crv: "Ed25519", x: input.publicKey },
      format: "jwk",
    });
    return verify(null, Buffer.from(input.message, "utf8"), key, signature);
  } catch {
    return false;
  }
}
