/**
 * Candidate-vocabulary pipeline (RAW CORPUS → TOKENIZE → NORMALIZE → FREQUENCY
 * → FILTER → CLASSIFY → GATE → TSV). Frequency is EVIDENCE, never truth.
 *
 *   npx tsx scripts/spell-extract-corpus-forms.ts [--write]
 *
 * Sources are TORE-authored Mongolian text only (UI copy, prompts, messages,
 * curriculum/fixtures inside this repository). No third-party word lists.
 * Output: src/spell-engine/data/sources/corpus-forms.tsv (accepted forms) and a
 * rejection report on stdout. Accepted forms ship as `form`-only entries in a
 * SEED pack: they make the exact surface form VALID, generate no paradigm,
 * and never enable edit-distance accusation.
 */
import fs from "node:fs";
import path from "node:path";

import { BUNDLED_PACKS, createSpellEngineV1 } from "../src/spell-engine/bundled";
import { lex } from "../src/spell-engine/tokenizer/lexer";

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "src/spell-engine/data/sources/corpus-forms.tsv");

// ── RAW CORPUS: explicit allow-list of TORE-authored sources ────────────────
function walk(dir: string, out: string[] = []): string[] {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (/\.(ts|tsx)$/.test(e.name)) out.push(p);
  }
  return out;
}
const EXCLUDE = [/src\/spell-engine\//, /src\/generated\//, /\.test\./, /src\/domain\/mongolian-orthography\//, /src\/engine\/knowledge\//];
const files = walk(path.join(ROOT, "src")).filter((f) => !EXCLUDE.some((re) => re.test(f)));
files.push(...["scripts/lib/student-curriculum-corpus.ts", "scripts/lib/fixture-legal-corpus.ts"].map((f) => path.join(ROOT, f)));

type Stat = { lower: number; midCapital: number; initialCapital: number; upper: number; files: Set<string> };
const stats = new Map<string, Stat>();

for (const file of files) {
  const text = fs.readFileSync(file, "utf8");
  if (!/[Ѐ-ӿ]/u.test(text)) continue;
  for (const t of lex(text)) {
    if (t.kind !== "WORD") continue;
    const w = t.text;
    if (!/^[а-яёөүА-ЯЁӨҮ]+$/u.test(w)) continue; // hyphenated / apostrophe / mixed → out
    const key = w.toLowerCase();
    const s = stats.get(key) ?? { lower: 0, midCapital: 0, initialCapital: 0, upper: 0, files: new Set<string>() };
    if (w === w.toUpperCase() && w.length > 1) s.upper += 1;
    else if (w === w.toLowerCase()) s.lower += 1;
    else if (t.sentenceInitial) s.initialCapital += 1;
    else s.midCapital += 1;
    s.files.add(path.relative(ROOT, file));
    stats.set(key, s);
  }
}

// ── FILTER / CLASSIFY / GATE ────────────────────────────────────────────────
// Judge candidates against everything EXCEPT the corpus pack itself, so re-running is idempotent.
const engine = createSpellEngineV1({ packs: BUNDLED_PACKS.filter((p) => p.id !== "tore-corpus-forms") });
const reasons = new Map<string, string[]>();
const reject = (r: string, w: string) => reasons.set(r, [...(reasons.get(r) ?? []), w]);
const accepted: { w: string; freq: number; files: number }[] = [];
let alreadyValid = 0;

for (const [w, s] of [...stats.entries()].sort((a, b) => a[0].localeCompare(b[0], "mn"))) {
  const freq = s.lower + s.midCapital + s.initialCapital + s.upper;
  if (w.length < 3) { reject("too-short", w); continue; }
  if (w.length > 24) { reject("too-long", w); continue; }
  if (/(.)\1\1/u.test(w)) { reject("repeated-letters", w); continue; }
  if (!/[аэиоуөүеяюёы]/u.test(w)) { reject("no-vowel", w); continue; }
  if (/ъ$/u.test(w)) { reject("hard-sign-final", w); continue; }
  if (s.upper > 0 && s.upper >= s.lower) { reject("acronym-candidate", w); continue; }
  if (s.midCapital > s.lower) { reject("proper-name-candidate", w); continue; }
  const verdict = engine.checkWord(w);
  if (verdict.verdict === "VALID") { alreadyValid += 1; continue; }
  if (verdict.verdict === "MISSPELLED") { reject("engine-says-misspelled (review: typo in copy or engine FP)", w); continue; }
  // Evidence gate: attested in ≥2 independent files, or ≥3 times, in lower case at least once.
  if (s.lower === 0) { reject("never-lower-case", w); continue; }
  if (s.files.size < 2 && freq < 3) { reject("single-attestation", w); continue; }
  accepted.push({ w, freq, files: s.files.size });
}

console.log(`sources: ${files.length} files; distinct Cyrillic word types: ${stats.size}; already VALID in current lexicon/morphology: ${alreadyValid}; ACCEPTED new forms: ${accepted.length}`);
for (const [r, list] of reasons) console.log(`  rejected ${String(list.length).padStart(5)}  ${r}${list.length <= 12 ? "  → " + list.join(", ") : ""}`);

if (process.argv.includes("--write")) {
  const header = "# Surface forms attested in TORE-authored Mongolian text (UI copy, messages, curriculum).\n# word<TAB>freq<TAB>files. Evidence-gated, form-only (no paradigm). Generated by\n# scripts/spell-extract-corpus-forms.ts — review before extending; not linguistic truth.\n";
  fs.writeFileSync(OUT, header + accepted.map((a) => `${a.w}\t${a.freq}\t${a.files}`).join("\n") + "\n");
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
}
